/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import interno.CartillaMilitar;
import interno.ColaDinamica;
import interno.Nodo;
import interno.PilaDinamica;
import javax.swing.JOptionPane;

/**
 *
 * @author Reyno21
 */
public class Menu extends javax.swing.JFrame
{
    public static ColaDinamica general;
    public static boolean ban = false;

    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
        if(!ban){
            general = new ColaDinamica();
            ban = true;
        }
    }
    
    public void mostrarTodos()
    {
        PilaDinamica tmp = new PilaDinamica();
        int tamanio = Menu.general.getTam();
        String matriz[][] = new String[tamanio][3];
        for (int i = 0; i < tamanio; i++)
        {
            Nodo aux = Menu.general.elimina();
            CartillaMilitar obj = (CartillaMilitar) aux.getObj();
            matriz[i][0] = obj.getNombre();
            matriz[i][1] = obj.getClase() + "";
            matriz[i][2] = obj.getRemiso() + "";
            tmp.inserta(aux);
        }

//        tablaPri.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]
//        {
//            "Nombre","Clase","Remisos"
//        })
//              
//        {
//            @Override
//            public boolean isCellEditable(int filas, int columnas)
//            {
//                if (columnas != 0)
//                {
//                    return true;
//                } else
//                {
//                    return false;
//                }
//            }
//        }
//        );
//        tablaPri.setEnabled(false);
//        
//        Nodo aux  = tmp.elimina();
//        while (aux != null)
//        {
//            Index.general.inserta(aux);
//            aux = tmp.elimina();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtBuscar = new javax.swing.JTextField();
        jbBusacar = new javax.swing.JButton();
        txtLista = new javax.swing.JButton();
        jbRemisos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtBuscarActionPerformed(evt);
            }
        });

        jbBusacar.setText("Buscar");
        jbBusacar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbBusacarActionPerformed(evt);
            }
        });

        txtLista.setText("Mostrar Todos");

        jbRemisos.setText("Remisos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRemisos)
                    .addComponent(txtLista)
                    .addComponent(jbBusacar))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBusacar))
                .addGap(64, 64, 64)
                .addComponent(txtLista)
                .addGap(18, 18, 18)
                .addComponent(jbRemisos)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtBuscarActionPerformed
    {//GEN-HEADEREND:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jbBusacarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbBusacarActionPerformed
    {//GEN-HEADEREND:event_jbBusacarActionPerformed
        // TODO add your handling code here:
        
        
        
        PilaDinamica tmp = new PilaDinamica();
        Nodo aux = general.elimina();
        Nodo enc = null;
        
        while (aux!= null)
        {
            if (aux.getEtq().compareTo(txtBuscar.getText()) !=0)
            {
                tmp.inserta(aux);
                aux=general.elimina();
                
            } else
            {
                enc = aux;
                tmp.inserta(aux);
                break;
            }
            
        }
        if (enc == null)
        {
            JOptionPane.showMessageDialog(this, "No se encontro el dato");
        } else
        {
            
        }
        
        aux = tmp.elimina();
        while (aux != null)
        {            
            general.inserta(aux);
            aux = tmp.elimina();
        }
    }//GEN-LAST:event_jbBusacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBusacar;
    private javax.swing.JButton jbRemisos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JButton txtLista;
    // End of variables declaration//GEN-END:variables
}
